
[screens]
	escapeMenuModifierPatch = true
	worldLoadModifierPatch = true
	serverConnectModifierPatch = true
	mainMenuModifierPatch = true

[discord]
	forceDisableDiscordRpc = true

[misc]
	pixelmonIconPatch = true
	serverListPatch = true

