
[general]
	show_compass = true
	show_owned = true
	show_shiny = true
	show_legendary = true
	show_boss = true
	show_palettes = true
	show_npc = true
	show_pokestop = true
	show_pokeballs = true
	show_raid = true
	pokemon_name = ""
	pokemon_gender = "pokehud.search.list.any"
	pokemon_growth = "pokehud.search.list.any"
	pokemon_palette = "pokehud.search.list.any"
	pokemon_form = "pokehud.search.list.any"

